spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_ban_sach
    username: root
    password: 12345

    hikari:
      maximum-pool-size: 100
      minimum-idle: 10


  data:
    redis:
      timeout: 10000
      cluster:
        nodes:
          - 192.168.0.101:6379
          - 192.168.0.101:6380
          - 192.168.0.101:6381
          - 192.168.0.101:6382
          - 192.168.0.101:6383
          - 192.168.0.101:6384
        max-redirects: 3
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 60s