spring:
  elasticsearch:
    uris: http://localhost:9200
    # Nếu có bảo mật, thêm username và password bên dưới
    # username: elastic
    # password: your_password
  profiles:
    active: uat

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: loog5277@gmail.com
    password: vqabvcgsgomlvxom
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  tomcat:
    accept-count: 3000
    max-connections: 10000
    connection-timeout: 20000
    threads:
      max: 400
      min-spare: 100
logging:
  level:
    PERF_LOGGER: OFF